version: '3.8'

services:

  racecar:
    build: .
    image: sebagarc/racecar2
    ports:
      - 6080:6080 # VNC
      - 11311:11311 # ROS master
    entrypoint: entrypoint.sh
    volumes:
      - ./home:/home/racecar
